services:
  minio:
    image: minio/minio:latest
    container_name: minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # MinIO Console
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - ./data/minio:/data

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: hive
      POSTGRES_PASSWORD: hive
      POSTGRES_DB: metastore
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  hive-metastore:
    image: apache/hive:3.1.3
    container_name: hive-metastore
    environment:
      SERVICE_NAME: metastore
      DATABASE_TYPE: postgres
      DATABASE_DRIVER: org.postgresql.Driver
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: metastore
      DATABASE_USER: hive
      DATABASE_PASSWORD: hive
      HIVE_AUX_JARS_PATH: /opt/hive/extra-jars
    ports:
      - "9083:9083"
    depends_on:
      - postgres
    volumes:
      - ./jars:/opt/hive/jars

  trino:
    image: trinodb/trino:422
    container_name: trino
    ports:
      - "8080:8080"
    volumes:
      - ./trino/catalog:/etc/trino/catalog
    depends_on:
      - hive-metastore

  spark:
    image: bitnami/spark:3.3.2
    container_name: spark
    environment:
      SPARK_MODE: master
      AWS_ACCESS_KEY_ID: minio
      AWS_SECRET_ACCESS_KEY: minio123
      AWS_REGION: us-east-1
    volumes:
      - ./ingest:/ingest
      - ./data:/data
      - ./jars:/opt/bitnami/spark/extra-jars
    depends_on:
      - hive-metastore
      - minio
    stdin_open: true
    tty: true
